version: '3.8'

services:
  backend:
    image: cool-tour
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./application.properties:/app/src/main/resources/application.properties
    depends_on:
      - database

  database:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dians
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data